# Generated by Django 6.0.2 on 2026-02-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio'), ('EQUIPO', 'Equipo')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_inventario', models.CharField(choices=[('NORMAL', 'Stock Normal'), ('CONSIGNACION', 'Consignación'), ('DROPSHIPPING', 'Dropshipping'), ('SERVICIO', 'Servicio')], default='NORMAL', max_length=20)),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidad'), ('HORA', 'Hora'), ('DIA', 'Día'), ('MES', 'Mes'), ('PAQUETE', 'Paquete')], default='UNIDAD', max_length=20)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_renta_dia', models.DecimalField(decimal_places=2, default=0, help_text='Precio de renta por día', max_digits=10)),
                ('itbis', models.DecimalField(decimal_places=2, default=18.0, help_text='ITBIS (%) aplicable', max_digits=5)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('stock_maximo', models.IntegerField(default=100)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200)),
                ('proveedor_contacto', models.CharField(blank=True, max_length=200)),
                ('permite_venta', models.BooleanField(default=True)),
                ('permite_renta', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EquipoRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RENTADO', 'Rentado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('DAÑADO', 'Dañado')], default='DISPONIBLE', max_length=20)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha_adquisicion', models.DateField()),
                ('ultima_fecha_mantenimiento', models.DateField(blank=True, null=True)),
                ('proxima_fecha_mantenimiento', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('producto', models.ForeignKey(limit_choices_to={'permite_renta': True}, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Equipo de Renta',
                'verbose_name_plural': 'Equipos de Renta',
            },
        ),
    ]
