# Generated by Django 6.0.2 on 2026-02-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaNCF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('B01', 'Facturas de Crédito Fiscal'), ('B02', 'Facturas de Consumo'), ('B14', 'Régimen Especial de Tributación'), ('B15', 'Gubernamental'), ('B16', 'Exportaciones')], max_length=3, unique=True)),
                ('serie', models.CharField(default='E', help_text='Serie del NCF (ej: E)', max_length=1)),
                ('numero_actual', models.IntegerField(default=1)),
                ('numero_desde', models.IntegerField(default=1)),
                ('numero_hasta', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Secuencia NCF',
                'verbose_name_plural': 'Secuencias NCF',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('ncf', models.CharField(blank=True, help_text='Número de Comprobante Fiscal (DGII)', max_length=13, unique=True)),
                ('tipo_ncf', models.CharField(blank=True, max_length=3)),
                ('tipo_ingreso', models.CharField(choices=[('PRODUCTO', 'Venta de Producto'), ('SERVICIO', 'Servicio'), ('RENTA', 'Renta'), ('IGUALA', 'Iguala')], max_length=20)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('itbis', models.DecimalField(decimal_places=2, default=0, help_text='Impuesto ITBIS (18%)', max_digits=12)),
                ('otros_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('PAGADA', 'Pagada'), ('PARCIAL', 'Pago Parcial'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('terminos_condiciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('itbis_porcentaje', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('itbis_monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Item de Factura',
                'verbose_name_plural': 'Items de Factura',
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, unique=True)),
                ('ncf', models.CharField(blank=True, max_length=13, unique=True)),
                ('fecha_emision', models.DateField()),
                ('motivo', models.CharField(choices=[('DEVOLUCION', 'Devolución'), ('DESCUENTO', 'Descuento'), ('ERROR', 'Error en Factura'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('factura_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=50, unique=True)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito')], max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='Número de cheque, referencia de transferencia, etc.', max_length=100)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.CharField(max_length=100)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
