# Generated by Django 6.0.2 on 2026-02-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('tipo_empleado', models.CharField(choices=[('TECNICO', 'Técnico'), ('VENDEDOR', 'Vendedor'), ('ADMINISTRATIVO', 'Administrativo'), ('GERENTE', 'Gerente')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('VACACIONES', 'De Vacaciones'), ('LICENCIA', 'En Licencia')], default='ACTIVO', max_length=20)),
                ('puesto', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especialidades', models.TextField(blank=True, help_text='Especialidades técnicas, separadas por comas')),
                ('certificaciones', models.TextField(blank=True)),
                ('horario_trabajo', models.CharField(default='8am-5pm Lun-Vie', max_length=200)),
                ('disponible_emergencias', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, upload_to='fotos_empleados/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('LICENCIA', 'Licencia'), ('CAPACITACION', 'Capacitación'), ('AUSENCIA', 'Ausencia')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
                ('aprobado_por', models.CharField(blank=True, max_length=100)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
            },
        ),
        migrations.CreateModel(
            name='AsignacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='ASIGNADA', max_length=20)),
                ('horas_estimadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('horas_reales', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.ordenservicio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.empleado')),
            ],
            options={
                'verbose_name': 'Asignación de Servicio',
                'verbose_name_plural': 'Asignaciones de Servicio',
            },
        ),
        migrations.CreateModel(
            name='AsignacionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(help_text='Rol del empleado en este contrato', max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('es_responsable_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.contratoservicio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.empleado')),
            ],
            options={
                'verbose_name': 'Asignación a Contrato',
                'verbose_name_plural': 'Asignaciones a Contratos',
            },
        ),
        migrations.CreateModel(
            name='RendimientoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Mes/Año del reporte')),
                ('servicios_asignados', models.IntegerField(default=0)),
                ('servicios_completados', models.IntegerField(default=0)),
                ('servicios_a_tiempo', models.IntegerField(default=0)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, help_text='Calificación promedio 1-5', max_digits=3)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
            ],
            options={
                'verbose_name': 'Rendimiento',
                'verbose_name_plural': 'Rendimientos',
                'unique_together': {('empleado', 'periodo')},
            },
        ),
    ]
