# Generated by Django 6.0.2 on 2026-02-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_emision', models.DateField()),
                ('vigencia_dias', models.IntegerField(choices=[(7, '7 días'), (15, '15 días'), (30, '30 días'), (60, '60 días'), (90, '90 días')], default=30)),
                ('fecha_vencimiento', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('itbis', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('CONVERTIDA', 'Convertida a Factura')], default='BORRADOR', max_length=20)),
                ('fecha_respuesta_cliente', models.DateField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('terminos_condiciones', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('forma_pago', models.CharField(blank=True, max_length=200)),
                ('tiempo_entrega', models.CharField(blank=True, max_length=200)),
                ('factura_generada', models.CharField(blank=True, help_text='Número de factura generada', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='AprobacionCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(help_text='Nivel de aprobación')),
                ('aprobador', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='cotizaciones.cotizacion')),
            ],
            options={
                'verbose_name': 'Aprobación',
                'verbose_name_plural': 'Aprobaciones',
                'ordering': ['nivel', '-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('especificaciones', models.TextField(blank=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('itbis_porcentaje', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('itbis_monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orden', models.IntegerField(default=0)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.cotizacion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Item de Cotización',
                'verbose_name_plural': 'Items de Cotización',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ENVIO', 'Envío'), ('LLAMADA', 'Llamada'), ('EMAIL', 'Email'), ('REUNION', 'Reunión'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('proximo_seguimiento', models.DateField(blank=True, null=True)),
                ('realizado_por', models.CharField(max_length=100)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='cotizaciones.cotizacion')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
